import Head from "next/head";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import VideosContainer from "../components/VideosContainer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Youtube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className=" flex w-full border">
        <Sidebar />
        <VideosContainer />
      </div>
    </div>
  );
}
