import Head from "next/head";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import VideosContainer from "../components/VideosContainer";
import {useState, useContext} from "react"
import { AuthCheckContext } from "../components/AuthCheck";

export default function Home() {
  const {user} = useContext(AuthCheckContext)
  const [notSignedIn, setNotSignedIn] = useState(false)
  const checkUser = () => {
    if (user) {
      setNotSignedIn(false)
    } else {
      setNotSignedIn(true)
    }
  }
  return (
    <div>
      <Head>
        <title>Youtube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header signInStatus={notSignedIn}/>
      <div className=" flex w-full">
        <Sidebar clicked={checkUser} />
        <VideosContainer />
      </div>
    </div>
  );
}
